/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1liJTyfJuIl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Payment({price, discount}: {price: number, discount: number}) {
  return (
    <Card className="w-full max-w-md p-6 rounded-lg shadow-lg">
      <div className="space-y-4">
      <header className="bg-primary text-primary-foreground py-4 px-6 rounded-t-lg">
          <h2 className="text-2xl font-bold">Order Summary</h2>
        </header>
        {/* <div className="flex justify-between">
          <span>1x Tedx SJEC pass</span>
          <span>₹{price}</span>
        </div>
        <hr className="my-4" /> */}
        <div className="flex justify-between">
          <span>Subtotal</span>
          <span>₹{price}</span>
        </div>
        <div className="flex justify-between">
          <span>Discount</span>
          <span>₹{discount} (10%)</span>
        </div>
        <hr className="my-4" />
        <div className="flex justify-between font-bold">
          <span>Total Amount</span>
          <span>₹{price-discount}</span>
        </div>
        <Button className="w-full bg-[#000000] text-white py-2 mt-4">Confirm and update</Button>
        {/* <div className="p-4 mt-4 bg-yellow-100 rounded-lg text-yellow-800">
          Your trial will end immediately and your card will be charged
        </div> */}
      </div>
    </Card>
  )
}
